Feature/points count
Herdran/Oil-Spill-Simulation pull request #20
Opened 2023-12-08 20:06 UTC by Mapet13

2023-12-09 17:51 UTC, Mapet13 commented on src/simulation/topology.py
> +        lat = binary_map_coordinates.longitude - top_left_binary_map_offset.longitude
error in names

2023-12-10 18:41 UTC, Herdran approved these changes

2023-12-10 18:41 UTC, Herdran commented on src/constatnts.py
> +    def get_center(first, direction, index) -> float:
Type hints for parameters

2023-12-16 16:37 UTC, bblachut requested changes

2023-12-16 16:37 UTC, bblachut commented on src/checkpoints.py
> +    lon, lat = get_coordinate_from_xy(x, y).as_tuple()
Why is it done different way than in function for point above?

2023-12-16 16:37 UTC, bblachut commented on src/checkpoints.py
> +    checkpoint_dir_path.mkdir(parents=True, exist_ok=True)
Why "parents=True"? If parents don't exists something is definitely not right

2023-12-16 16:37 UTC, bblachut commented on src/gui/main_screen.py
> +                    if self.viewer.top <= coords[1] <= self.viewer.bottom and self.viewer.left <= coords[0] <= self.viewer.right:
Shouldn't the second comparison be < instead of  <= for both x and y?

2023-12-16 16:37 UTC, bblachut commented on src/initial_values_loader.py
> +logger = getLogger("constants")
initial_values not constants

2023-12-16 16:37 UTC, bblachut commented on src/log_config.conf
> +[logger_constants]
initial_values not constants

2023-12-16 16:37 UTC, bblachut commented on src/topology/math.py
> +    return (x, y)
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/topology/math.py
> +    return (bearing, dist)
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/topology/math.py
> +    return (point.latitude, point.longitude)
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/topology/binary_map_math.py
> +    return (lon, lat)
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/topology/binary_map_math.py
> +    return (int(x), int(y))
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/data/measurement_data.py
> +        return (self.latitude, self.longitude)
Remove parenthesis

2023-12-16 16:37 UTC, bblachut commented on src/topology/math.py
> +class Move_direction(Enum):
CamelCase

2023-12-16 16:37 UTC, bblachut commented on src/topology/math.py
> +def move_coordinate_raw(lat: float, lon: float, distance: float, direction: Move_direction) -> (float, float):
In return type hints use Tuple[], applicable everywhere I posted comment about redundant parenthesis

2023-12-16 18:17 UTC, Mapet13 commented on src/checkpoints.py
> +    lon, lat = get_coordinate_from_xy(x, y).as_tuple()
get_coordinate was intended to be point's internal method (and yes, I forgot to use _ sign) that caches results. 
But actually that could be also used here, I will change my initial assumption.

2023-12-16 18:29 UTC, Mapet13 commented on src/checkpoints.py
> +    checkpoint_dir_path.mkdir(parents=True, exist_ok=True)
> If parents is true, any missing parents of this path are created as needed; they are created with the default permissions without taking mode into account (mimicking the POSIX mkdir -p command).

^ from https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

2023-12-16 18:31 UTC, Mapet13 commented on src/gui/main_screen.py
> +                    if self.viewer.top <= coords[1] <= self.viewer.bottom and self.viewer.left <= coords[0] <= self.viewer.right:
@Herdran

2023-12-16 19:51 UTC, bblachut approved these changes

2023-12-16 19:53 UTC, merged